#AWS::Route53::HostedZone
#http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html
#
#To declare this entity in your AWS CloudFormation template, use the following syntax:

Type: "AWS::Route53::HostedZone"
Properties: 
  HostedZoneConfig:
    HostedZoneConfig
  HostedZoneTags:
    -  HostedZoneTags
  Name: String
  VPCs:
    - HostedZoneVPCs 
#
#The following template snippet creates a private hosted zone for the example.com domain.

DNS: 
  Type: "AWS::Route53::HostedZone"
  Properties: 
    HostedZoneConfig: 
      Comment: "My hosted zone for example.com"
    Name: "example.com"
    VPCs: 
      - 
        VPCId: "vpc-abcd1234"
        VPCRegion: "ap-northeast-1"
      - 
        VPCId: "vpc-efgh5678"
        VPCRegion: "us-west-2"
    HostedZoneTags: 
      - 
        Key: "SampleKey1"
        Value: "SampleValue1"
      - 
        Key: "SampleKey2"
        Value: "SampleValue2"